environment_variables: {}
external_package_dirs: []
model_metadata: {}
model_name: Llama 2 7B
python_version: py310
requirements: []
resources:
  accelerator: null
  cpu: '1'
  memory: 2Gi
  use_gpu: false
secrets: {}
system_packages: []
